import test from 'node:test';
import assert from 'node:assert/strict';
import {Ledger,memoryAdapter} from '../server/store.mjs';
import {createApplication} from '../server/application.mjs';
import {hash,token,totp,base32} from '../server/auth.mjs';
const origin='https://misxv.simplysoph.com',at=Date.parse('2026-10-01T18:00:00Z');
const household='12345678-1234-1234-1234-123456789012';
async function fixture(){const ledger=new Ledger(memoryAdapter()),adminToken=token(),guestToken=token();const row={id:household,name:'Test family',capacity:{adultsTeens:2,kids:1},email:'test@example.com',phone:'',validCapacity:true,archived:false};let failing=false,sendCount=0;
 const notion={async read(){return structuredClone(row);},async list(){return [structuredClone(row)];},async project(){if(failing)throw {code:'NOTION_UNAVAILABLE'};},async prepareSchema(){return [];}};
 const mailer={configured:true,async send(){sendCount++;}};
 const app=createApplication({ledger,notion,mailer,verifyGoogle:async()=>({id:'organizer',email:'organizer@gmail.com'}),media:{put:async()=>{},get:async()=>Buffer.from('image')},key:Buffer.alloc(32,4),origin,adminEmails:['organizer@gmail.com'],now:()=>at});
 await ledger.transaction(s=>{s.sessions[hash(adminToken)]={kind:'admin',actor:'organizer',email:'organizer@gmail.com',csrf:'admin-csrf',expiresAt:at+100000};s.invitations[household]={id:household,name:row.name,active:true,generation:1,tokenHash:hash(guestToken),invited:{ceremony:true,dinner:true,dance:false}};});
 const admin=(path,body)=>app.dispatch({path:'/api/admin/'+path,method:body?'POST':'GET',body,headers:{origin,cookie:'__session='+adminToken,'x-csrf-token':'admin-csrf'},ip:'admin'});
 const login=await app.dispatch({path:'/api/invitation-session',method:'POST',body:{token:guestToken},headers:{origin},ip:'guest'}),guestCookie=login.setCookie.split(';')[0];
 const guest=(path,body,headers={})=>app.dispatch({path:'/api/'+path,method:body?'POST':'GET',body,headers:{origin,cookie:guestCookie,'x-csrf-token':login.csrf,...headers},ip:'guest'});
 const input=()=>({previousSubmissionId:null,attendance:{ceremony:{adultsTeens:1,kids:0},dinner:{adultsTeens:2,kids:1},dance:{adultsTeens:0,kids:0}},contact:{email:'test@example.com',phone:'',address:null},requests:''});
 return {app,ledger,admin,guest,input,row,guestToken,failSync:()=>failing=true,sends:()=>sendCount};}
test('durable receipts survive reopening; duplicate submit is one response and one email draft',async()=>{const f=await fixture(),data=f.input();const one=await f.guest('rsvp',data,{'idempotency-key':'request-0001'});assert.equal(one.saved,true);const again=await f.guest('rsvp',data,{'idempotency-key':'request-0001'});assert.equal(again.id,one.id);const restored=await f.guest('invitation');assert.equal(restored.response.id,one.id);const s=await f.ledger.read();assert.equal(Object.keys(s.responses).length,1);assert.equal(Object.keys(s.outbox).length,1);assert.equal(f.sends(),0);});
test('concurrent different submissions cannot both replace the same previous response',async()=>{const f=await fixture();const results=await Promise.allSettled([f.guest('rsvp',f.input(),{'idempotency-key':'concurrent-1'}),f.guest('rsvp',f.input(),{'idempotency-key':'concurrent-2'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);});
test('Notion outage preserves accepted response and exposes pending sync without duplicate email',async()=>{const f=await fixture();f.failSync();const result=await f.guest('rsvp',f.input(),{'idempotency-key':'request-0002'});assert.equal(result.syncState,'pending');assert.equal((await f.guest('invitation')).response.id,'request-0002');});
test('guest access cannot call admin or override capacities; revocation invalidates an active session',async()=>{const f=await fixture();await assert.rejects(()=>f.guest('admin/dashboard'),e=>e.status===401);const data=f.input();data.attendance.dinner.kids=2;await assert.rejects(()=>f.guest('rsvp',data,{'idempotency-key':'request-0003'}),e=>e.status===422);await f.admin('revoke',{id:household});await assert.rejects(()=>f.guest('invitation'),e=>e.status===401);});
test('origin and csrf checks reject writes; changed fresh Notion capacity rejects an open form',async()=>{const f=await fixture();await assert.rejects(()=>f.guest('rsvp',f.input(),{origin:'https://evil.example','idempotency-key':'request-0004'}),e=>e.status===403);await assert.rejects(()=>f.guest('rsvp',f.input(),{'x-csrf-token':'bad','idempotency-key':'request-0004'}),e=>e.status===403);f.row.capacity.kids=0;await assert.rejects(()=>f.guest('rsvp',f.input(),{'idempotency-key':'request-0004'}),e=>e.status===422);});
test('MFA is required; invalid attempts persist and valid code cannot be reused',async()=>{const f=await fixture();const request=body=>f.app.dispatch({path:'/api/auth/google',method:'POST',headers:{origin},body,ip:'new-admin'});const login=await request({credential:'verified-by-fixture'});const code=totp(login.enrollmentSecret,Math.floor(at/30000));const verify=body=>f.app.dispatch({path:'/api/auth/mfa',method:'POST',headers:{origin},body,ip:'new-admin'});await assert.rejects(()=>verify({challenge:login.challenge,code:'bad'}),e=>e.code==='INVALID_MFA');assert.equal((await f.ledger.read()).challenges[hash(login.challenge)].attempts,1);const signed=await verify({challenge:login.challenge,code});assert.match(signed.setCookie,/HttpOnly; Secure/);const again=await request({credential:'verified-by-fixture'});await assert.rejects(()=>verify({challenge:again.challenge,code}),e=>e.code==='INVALID_MFA');});
test('TOTP follows RFC 6238 SHA1 vector at 59 seconds (six digit suffix)',()=>{const secret=base32(Buffer.from('12345678901234567890'));assert.equal(totp(secret,1),'287082');});
test('guestbook stays private pending moderation; contact messages cannot be published',async()=>{const f=await fixture();const message=await f.guest('messages',{kind:'guestbook',name:'Test',text:'Best wishes',consent:true});const pub=()=>f.app.dispatch({path:'/api/public',method:'GET'});assert.equal((await pub()).messages.length,0);await f.admin('moderation',{collection:'messages',id:message.id,state:'approved'});assert.equal((await pub()).messages.length,1);const contact=await f.guest('messages',{kind:'contact',name:'Test',text:'Private question'});await assert.rejects(()=>f.admin('moderation',{collection:'messages',id:contact.id,state:'approved'}),e=>e.status===422);});
test('seating rejects over-capacity and duplicate placement; email never sends twice',async()=>{const f=await fixture();await f.guest('rsvp',f.input(),{'idempotency-key':'request-0005'});await assert.rejects(()=>f.admin('seating',{name:'Small table',capacity:2,households:[household]}),e=>e.status===422);await f.admin('seating',{name:'Table 1',capacity:8,households:[household]});await assert.rejects(()=>f.admin('seating',{name:'Table 2',capacity:8,households:[household]}),e=>e.status===409);const id=Object.keys((await f.ledger.read()).outbox)[0];await f.admin('mail/send',{id,confirm:true});await assert.rejects(()=>f.admin('mail/send',{id,confirm:true}),e=>e.status===409);assert.equal(f.sends(),1);});

