import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import {event,routes,adminRoutes,copy,textContent} from '../site/content.mjs';
const root=new URL('../dist/',import.meta.url),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const href=(route,lang)=>`${lang==='es'?'/es':''}/${route?route+'/':''}`;
function contents(route,lang){const es=lang==='es',t=copy[lang],say=(a,b)=>es?b:a,link=(r,label)=>`<a class="button burgundy" href="${href(r,lang)}">${label}</a>`;
 if(route==='')return `<section class="hero"><div class="hero-copy"><p class="eyebrow">MIS XV · FORT WORTH</p><h1>Sophia</h1><p class="hero-line">${t.tagline}</p><p class="date">${t.date}</p><p>${t.intro}</p><div class="actions">${link('rsvp',t.rsvp)}<a href="${href('details',lang)}">${t.all} ↗</a></div><div class="countdown" data-countdown aria-label="${say('Days until the celebration','Días hasta la celebración')}"></div></div><figure class="invitation"><a href="/assets/invitation.png"><img src="/assets/invitation.png" width="1024" height="1536" alt="${say('Sophia’s gold and burgundy invitation','Invitación de Sophia en dorado y borgoña')}"></a><figcaption>${t.dateCorrection}</figcaption></figure></section><section class="section"><p class="eyebrow">${say('THE NEXT CHAPTER','EL PRÓXIMO CAPÍTULO')}</p><h2>${say('A day made for memories.','Un día para crear recuerdos.')}</h2><div class="cards">${[['sophia',say('Meet Sophia','Conoce a Sophia')],['details',t.details],['gallery',say('The moments','Los momentos')]].map(([r,label])=>`<a class="card" href="${href(r,lang)}"><span>✦</span><h3>${label}</h3><span aria-hidden="true">↗</span></a>`).join('')}</div><div data-announcements></div></section>`;
 const heading=`<div class="page-heading"><p class="eyebrow">SOPHIA · MIS XV</p><h1>${routes.find(r=>r[0]===route)?.[es?2:1]||'Sophia'}</h1></div>`;let body='';
 if(textContent[route]){const c=textContent[route];body=`<div class="editorial"><span class="ornament">✦</span><h2>${c[0][es?1:0]}</h2><p class="lead">${c[1][es?1:0]}</p><p>${c[2][es?1:0]}</p>${link('contact',t.contact)}</div>`;}
 if(route==='details')body=`<p class="lead">${t.date}</p><p>${t.time}</p><div class="cards">${[['ceremony','4:00 PM',say('Religious ceremony','Ceremonia religiosa')],['reception','6:30–7:30 PM',say('Dinner · location to be confirmed','Cena · lugar por confirmar')],['reception','7:30 PM',say('Reception & dance','Recepción y baile')]].map(([r,time,label])=>`<article class="card"><p class="eyebrow">${time}</p><h2>${label}</h2><a href="${href(r,lang)}">${say('Venue details','Detalles del lugar')} ↗</a></article>`).join('')}</div><div class="editorial"><h2>${say('Dress code','Código de vestimenta')}</h2><p>${t.pending} ${say('Burgundy and gold are the site theme, not a required outfit.','Borgoña y dorado son los colores del sitio, no una vestimenta obligatoria.')}</p><a href="/sophia-mis-xv.ics" download>${say('Save the date to your calendar','Guarda la fecha en tu calendario')}</a></div>`;
 if(route==='ceremony')body=`<div class="editorial"><p class="eyebrow">4:00 PM · ${t.date}</p><h2>${say('A moment of faith','Un momento de fe')}</h2><p>Lady of Guadalupe Church</p><p>${say('The exact church name, address, arrival time, parking and photography guidance are being confirmed. Directions will appear here once verified.','Estamos confirmando el nombre exacto de la iglesia, la dirección, la hora de llegada, el estacionamiento y las indicaciones para fotografías. Publicaremos las indicaciones cuando estén verificadas.')}</p>${link('details',t.details)}</div>`;
 if(route==='reception')body=`<div class="split"><article><p class="eyebrow">${say('RECEPTION & DANCE · 7:30 PM','RECEPCIÓN Y BAILE · 7:30 PM')}</p><h2>AMZ Event Center</h2><address>5103 Azle Ave, Unit 200<br>Fort Worth, TX 76114</address><a class="button burgundy" href="https://www.google.com/maps/search/?api=1&query=AMZ%20Event%20Center%205103%20Azle%20Ave%20Fort%20Worth%20TX%2076114" target="_blank" rel="noopener noreferrer">${say('Open map','Abrir mapa')} ↗</a></article><article class="card"><h3>${say('Before you arrive','Antes de llegar')}</h3><p>${say('Dinner is scheduled for 6:30–7:30 PM; its location is still being confirmed. Entrance, parking and accessibility details will be added here.','La cena está programada de 6:30 a 7:30 p. m.; el lugar está por confirmar. Agregaremos los detalles de entrada, estacionamiento y accesibilidad.')}</p></article></div>`;
 if(route==='rsvp'||route==='rsvp/confirmed')body=`<p class="deadline">${t.deadlineLabel} <strong>${t.deadline}</strong></p><div class="portal" id="portal" data-view="${route}"><p role="status">${t.loading}</p></div>`;
 if(route==='gallery')body=`<p class="lead">${say('Little moments, lasting memories.','Pequeños momentos, recuerdos para siempre.')}</p><div data-gallery class="cards"></div><p>${say('Approved photographs will appear here.','Aquí aparecerán las fotografías aprobadas.')}</p>${link('share',say('Share a photo','Comparte una foto'))}`;
 if(route==='share')body=`<p class="lead">${say('Share the celebration through your eyes.','Comparte la celebración desde tu mirada.')}</p><p>${say('Photos are reviewed by the family before appearing in the gallery. Use your private invitation to sign in.','La familia revisa las fotos antes de publicarlas en la galería. Inicia sesión con tu invitación privada.')}</p><div class="portal" id="portal" data-view="share"></div><a href="${href('terms',lang)}">${say('Photo sharing terms','Condiciones para compartir fotos')}</a>`;
 if(route==='guestbook'||route==='contact')body=`<p class="lead">${route==='guestbook'?say('Leave Sophia a wish for the years ahead.','Deja a Sophia un deseo para los años que vienen.'):say('We’re here to help with your invitation.','Estamos aquí para ayudarte con tu invitación.')}</p>${route==='contact'?`<p><a href="mailto:${event.sender}">${event.sender}</a></p>`:''}<div class="portal" id="portal" data-view="${route}"></div>${route==='guestbook'?'<div data-guestbook class="cards"></div>':''}`;
 if(route==='faq')body=[
 [say('When should I RSVP?','¿Cuándo debo confirmar?'),`${t.deadline}. ${say('Use the private invitation sent to your household.','Usa la invitación privada que recibió tu familia.')}`],
 [say('Can I bring a guest or children?','¿Puedo llevar acompañantes o niños?'),say('Your invitation specifies the adult/teen and child spaces allocated to your household. Contact the family if the information needs correcting.','Tu invitación indica los lugares para adultos/jóvenes y niños asignados a tu familia. Contacta a la familia si hay un error.')],
 [say('Can I change my response?','¿Puedo cambiar mi respuesta?'),say('Reopen your private invitation before the deadline. Your most recent saved response is the one counted.','Abre de nuevo tu invitación privada antes de la fecha límite. Se contará la última respuesta guardada.')],
 [say('What should I wear?','¿Cómo debo vestirme?'),t.pending],
 [say('Are gifts required?','¿Se requieren regalos?'),say('The family will share gift preferences on the Gifts page.','La familia compartirá sus preferencias en la página de regalos.')],
 [say('Can I share photos?','¿Puedo compartir fotos?'),say('Use Share photos and agree to the photo terms. Only approved images appear publicly.','Usa Comparte tus fotos y acepta las condiciones. Solo se publicarán imágenes aprobadas.')]
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')+`<p>${link('contact',t.contact)}</p>`;
 if(route==='privacy')body=`<article class="editorial"><h2>${say('Information for this celebration','Información para esta celebración')}</h2><p>${say('Private invitations use household contact details and allocated spaces. Responses collect attendance, contact corrections and optional requests. Photos and guestbook submissions are held for family review.','Las invitaciones privadas usan los datos de contacto y los lugares asignados a cada familia. Las respuestas incluyen asistencia, correcciones de contacto y solicitudes opcionales. Las fotos y mensajes se guardan para revisión de la familia.')}</p><p>${say('Authorized organizers use Notion and a private Google Cloud service to manage responses. Microsoft 365 is the planned email provider. Public pages never include the guest list.','Los organizadores autorizados usan Notion y un servicio privado de Google Cloud para administrar respuestas. Microsoft 365 es el proveedor previsto de correos. Las páginas públicas nunca incluyen la lista de invitados.')}</p><p>${say('Firebase Hosting serves the site. Google Fonts receives normal network information when fonts load. Administrator sign-in uses Google. We have added no advertising or analytics trackers.','Firebase Hosting aloja el sitio. Google Fonts recibe información de red al cargar fuentes. El acceso de administradores usa Google. No agregamos publicidad ni rastreadores de análisis.')}</p><h3>${say('Your choices','Tus opciones')}</h3><p>${say('Optional requests, mailing addresses, messages and photos are voluntary. Keep invitation links private. Contact the family to correct or remove information. The family must finalize a retention date before live collection opens.','Las solicitudes, direcciones postales, mensajes y fotos son opcionales. Mantén privados los enlaces de invitación. Contacta a la familia para corregir o eliminar información. La familia debe definir el plazo de retención antes de abrir la recopilación de datos.')}</p><a href="mailto:${event.sender}">${event.sender}</a></article>`;
 if(route==='terms')body=`<article class="editorial"><h2>${say('Share with care','Comparte con cuidado')}</h2><ul><li>${say('Upload only photos you took or have permission to share.','Sube solo fotos que tomaste o tienes permiso de compartir.')}</li><li>${say('Get permission from recognizable people and a parent or guardian for children.','Obtén permiso de las personas reconocibles y de un padre o tutor para menores.')}</li><li>${say('By submitting, you allow the family to review and display approved photos on this event website. The gallery may be publicly visible.','Al enviar, permites que la familia revise y publique fotos aprobadas en este sitio. La galería puede ser pública.')}</li><li>${say('Do not upload private documents, inappropriate content or images of anyone who does not want them shared.','No subas documentos privados, contenido inapropiado ni imágenes de personas que no quieran compartirlas.')}</li><li>${say('Images may be resized and metadata removed. Submissions can be declined or removed.','Las imágenes pueden cambiar de tamaño y perder metadatos. Los envíos pueden rechazarse o eliminarse.')}</li></ul><p>${say('To request removal, contact','Para solicitar la eliminación, escribe a')} <a href="mailto:${event.sender}">${event.sender}</a>.</p></article>`;
 if(route==='404')body=`<p class="lead">${say('Let’s get you back to the celebration.','Volvamos a la celebración.')}</p>${link('',t.home)}`;
 return `<section class="page section">${heading}${body}</section>`;
}
function navigation(lang,current){const t=copy[lang],label=r=>routes.find(p=>p[0]===r)?.[lang==='es'?2:1]||r;return `<header><a class="wordmark" href="${href('',lang)}">S <span>· MIS XV</span></a><nav aria-label="${lang==='es'?'Navegación principal':'Main navigation'}"><a href="${href('sophia',lang)}">Sophia</a>${[[t.details,['details','ceremony','reception']],[t.people,['court','padrinos']],[t.memories,['gallery','share','guestbook','thank-you']],[t.help,['travel','gifts','faq','contact']]].map(([name,items])=>`<details class="nav-group"><summary>${name}</summary><div>${items.map(r=>`<a href="${href(r,lang)}"${r===current?' aria-current="page"':''}>${label(r)}</a>`).join('')}</div></details>`).join('')}<a class="nav-rsvp" href="${href('rsvp',lang)}">RSVP</a><a class="language" lang="${lang==='es'?'en':'es'}" href="${href(current,lang==='es'?'en':'es')}">${t.language}</a></nav></header>`;}
function document({route,title,lang='en',admin=false}){const t=copy[lang];return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><meta name="description" content="${esc(t.tagline)}"><title>${esc(title)} · Sophia</title><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pages.css"><script type="module" src="/${admin?'admin':'guest'}.js"></script></head><body data-route="${route}"><a class="skip" href="#main">${lang==='es'?'Ir al contenido':'Skip to content'}</a>${navigation(lang,admin?'':route)}<main id="main">${admin?`<section class="section admin-shell"><aside aria-label="Family administration">${adminRoutes.filter(([r])=>r!=='admin/login').map(([r,t])=>`<a href="/${r}/"${r===route?' aria-current="page"':''}>${t}</a>`).join('')}<button class="plain-button" id="logout">Sign out</button></aside><div><p class="eyebrow">FAMILY ONLY</p><h1 class="page-title">${title}</h1><div id="admin-app" data-view="${route}"><p role="status">Loading secure workspace…</p></div></div></section>`:contents(route,lang)}</main><footer><p>${t.footer}<em>Sophia</em></p><span>MIS XV · ${t.date}</span><div><a href="${href('privacy',lang)}">${lang==='es'?'Privacidad':'Privacy'}</a> · <a href="${href('terms',lang)}">${lang==='es'?'Fotos':'Photo terms'}</a> · <a href="/admin/login/">${lang==='es'?'Familia':'Family'}</a></div></footer><div id="status" role="status" aria-live="polite"></div></body></html>`;}
await mkdir(root,{recursive:true});let count=0;
for(const lang of ['en','es'])for(const [route,en,es] of routes){const folder=new URL((lang==='es'?'es/':'')+(route?route+'/':''),root);await mkdir(folder,{recursive:true});const html=document({route,title:lang==='es'?es:en,lang});await writeFile(new URL('index.html',folder),html);if(route==='404'&&lang==='en')await writeFile(new URL('404.html',root),html);count++;}
for(const [route,title] of adminRoutes){const folder=new URL(route+'/',root);await mkdir(folder,{recursive:true});await writeFile(new URL('index.html',folder),document({route,title,admin:true}));count++;}
await mkdir(new URL('assets/',root),{recursive:true});
for(const file of ['styles.css','pages.css','guest.js','admin.js','client.js','event-config.js','assets/invitation.png'])await copyFile(new URL('../site/'+file,import.meta.url),new URL(file,root));
await writeFile(new URL('sophia-mis-xv.ics',root),['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//SimplySoph//Mis XV//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:misxv-20270115@simplysoph.com','DTSTAMP:20260927T000000Z','DTSTART:20270115T220000Z','SUMMARY:Sophia - Mis XV','DESCRIPTION:Ceremony 4 PM Central. Dinner 6:30-7:30 PM (location pending).',' Reception 7:30 PM at AMZ Event Center. Check website for venue details.','URL:https://misxv.simplysoph.com/details/','END:VEVENT','END:VCALENDAR',''].join('\r\n'));
await writeFile(new URL('robots.txt',root),'User-agent: *\nDisallow: /\n');
console.log(`Built ${count} pages, English/Spanish guest routes, private admin shells and calendar. Runtime features require the configured API.`);
