// Pure rendering only. No network, credentials, scheduling, or live dispatch.
const copy={
  en:{invitation:['You’re invited to Sophia’s Mis XV','A new chapter, shared with you.','We would love to celebrate with your household. Open your private invitation to see the details and respond.','View your invitation'],receipt:['We received your RSVP · Sophia’s Mis XV','Thank you for your response.','Your household’s response has been received. You can review your attendance and make permitted changes through your private invitation.','Review your response'],update:['Your RSVP has been updated · Sophia’s Mis XV','Your latest response is recorded.','Open your private invitation to review the most recently accepted answers for your household.','View updated response'],reminder:['A little reminder · Sophia’s Mis XV','Will you join us?','We are still waiting for all or part of your household’s response. Please use your private invitation to reply before the deadline.','Complete your RSVP'],details:['Before we celebrate · Sophia’s Mis XV','The celebration is almost here.','Please review the confirmed schedule, directions, arrival guidance, and any updates before the celebration.','View event details'],change:['An important update · Sophia’s Mis XV','Please review an event update.','The family has confirmed a change to the celebration. The details below explain what changed.','Read the update'],thanks:['With love and thanks · Sophia’s Mis XV','Thank you for being part of this chapter.','Your love and support mean so much to Sophia and her family. We are grateful to have you in our lives.','A message from Sophia'],greeting:'Hello',date:'Event date',deadline:'RSVP by',private:'This invitation link is for your household. Please keep it private.',help:'Questions? Reply to this email to reach the family.',sign:'With love, Sophia & Family',preview:'SAMPLE PREVIEW — NOT SENT'},
  es:{invitation:['Estás invitado a los XV de Sophia','Un nuevo capítulo, junto a ti.','Nos encantaría celebrar con tu familia. Abre tu invitación privada para ver los detalles y confirmar su asistencia.','Ver su invitación'],receipt:['Recibimos tu confirmación · Los XV de Sophia','Gracias por responder.','Recibimos la respuesta de tu familia. Puedes revisar su asistencia y hacer los cambios permitidos a través de su invitación privada.','Revisar su respuesta'],update:['Actualizamos tu respuesta · Los XV de Sophia','Tu nueva respuesta quedó registrada.','Abre su invitación privada para revisar las respuestas más recientes de tu familia.','Ver la respuesta actualizada'],reminder:['Un pequeño recordatorio · Los XV de Sophia','¿Nos acompañarán?','Aún nos falta toda o parte de la respuesta de tu familia. Usa su invitación privada para responder antes de la fecha límite.','Confirmar asistencia'],details:['Antes de celebrar · Los XV de Sophia','La celebración se acerca.','Revisa el programa confirmado, las direcciones, las indicaciones de llegada y cualquier novedad antes de la celebración.','Ver los detalles'],change:['Una actualización importante · Los XV de Sophia','Revisa este cambio del evento.','La familia confirmó un cambio en la celebración. Los detalles a continuación explican qué cambió.','Leer la actualización'],thanks:['Con cariño y gratitud · Los XV de Sophia','Gracias por ser parte de este capítulo.','Tu cariño y apoyo significan mucho para Sophia y su familia. Gracias por formar parte de nuestras vidas.','Un mensaje de Sophia'],greeting:'Hola',date:'Fecha del evento',deadline:'Confirma antes del',private:'Este enlace de invitación es para tu familia. Por favor, mantenlo privado.',help:'¿Tienes preguntas? Responde a este correo para comunicarte con la familia.',sign:'Con cariño, Sophia y su familia',preview:'VISTA PREVIA — NO ENVIADO'}
};
export const templateKeys=['invitation','receipt','update','reminder','details','change','thanks'];
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderEmail({type,locale='en',household='Sample household',url,eventDate,rsvpDeadline,updateText='',preview=true,dateConfirmed=false,receiptCommitted=false}){
  if(!templateKeys.includes(type)||!copy[locale])throw new Error('Unsupported template or locale');
  const target=new URL(url);
  if(target.protocol!=='https:'||target.username||target.password)throw new Error('An HTTPS URL without embedded credentials is required');
  if(!preview&&(!dateConfirmed||!eventDate||/\.example$/.test(target.hostname)))throw new Error('Confirmed event date and real destination required');
  if(!preview&&['receipt','update'].includes(type)&&!receiptCommitted)throw new Error('A committed response is required');
  if(!preview&&['invitation','reminder'].includes(type)&&!rsvpDeadline)throw new Error('RSVP deadline required');
  if(type==='change'&&!updateText.trim())throw new Error('Describe the approved event change');
  const c=copy[locale], [subject,title,intro,cta]=c[type];
  const lines=[preview?c.preview:'',`${c.greeting} ${household},`,title,intro,eventDate?`${c.date}: ${eventDate}`:'',rsvpDeadline&&['invitation','reminder'].includes(type)?`${c.deadline}: ${rsvpDeadline}`:'',updateText,`${cta}: ${target.href}`,c.private,c.help,c.sign].filter(Boolean);
  const html=`<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(subject)}</title></head><body style="margin:0;background:#fbf5e9;color:#351e21;font:16px/1.6 Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="560" style="width:100%;max-width:560px;background:#fffdf8;border:1px solid #d9c6a5" cellspacing="0" cellpadding="0"><tr><td style="background:#651625;color:#e9c77b;padding:28px;text-align:center;font:36px Georgia,serif">Sophia · Mis XV</td></tr><tr><td style="padding:28px">${preview?`<p style="font-size:13px;color:#651625">${c.preview}</p>`:''}<p>${escape(c.greeting)} ${escape(household)},</p><h1 style="font:30px/1.2 Georgia,serif;color:#651625">${escape(title)}</h1><p>${escape(intro)}</p>${eventDate?`<p><strong>${c.date}:</strong> ${escape(eventDate)}</p>`:''}${rsvpDeadline&&['invitation','reminder'].includes(type)?`<p><strong>${c.deadline}:</strong> ${escape(rsvpDeadline)}</p>`:''}${updateText?`<p>${escape(updateText)}</p>`:''}<p style="margin:28px 0"><a href="${escape(target.href)}" style="display:inline-block;background:#651625;color:#fff;padding:14px 22px;text-decoration:none">${escape(cta)}</a></p><p style="font-size:14px">${escape(c.private)}</p><p>${escape(c.help)}</p><p style="font-family:Georgia,serif">${escape(c.sign)}</p></td></tr></table></td></tr></table></body></html>`;
  return {subject,html,text:lines.join('\n\n')};
}
